[package]
name = "medo_watcher"
version = "0.1.0"
edition = "2021"
authors = ["Alex_Xar <P40b0s@gmail.com.com>"]

[dependencies]
serde = { version = "1.0.150", features = ["derive"] }

[workspace]
members = ["server", "frontend"]
default-members = ["server"]